export interface Broker { id:string; broker_id:string; name:string; email:string; phone:string; referral_code:string; parent_id:string|null; rank:string; status:string; total_sqyd:number; kyc_status:string; gst_no:string|null; pan_no:string|null; tds_applicable:boolean; created_at:string; updated_at:string }
export interface BpProject { id:string; name:string; location:string; description:string|null; total_plots:number; price_per_sqyd:number; status:string; rera_no:string|null; brochure_url:string|null; launch_date:string|null; site_manager:string|null; map_url:string|null; created_at:string; updated_at:string }
export interface BpPlot { id:string; project_id:string; plot_no:string; size_sqyd:number; category:string|null; facing:string|null; price_per_sqyd:number; total_price:number; status:string; floor:string|null; notes:string|null; block:string|null; sector:string|null; plc_charges:number; is_corner:boolean; created_at:string; updated_at:string; bp_projects?:BpProject }
export interface BpCustomer { id:string; name:string; phone:string; alt_phone:string|null; email:string|null; aadhaar:string|null; pan:string|null; address:string|null; city:string|null; state:string|null; notes:string|null; created_at:string; updated_at:string }
export interface BpBooking { id:string; booking_no:string; plot_id:string; customer_id:string; broker_id:string; project_id:string; stage:string; plot_total_price:number; token_amount:number|null; token_date:string|null; booking_amount:number|null; booking_date:string|null; full_payment_amount:number|null; full_payment_date:string|null; balance_due:number; total_collected:number; registry_date:string|null; registry_notes:string|null; commission_rate:number|null; commission_amount:number|null; commission_status:string; notes:string|null; created_by:string|null; created_at:string; updated_at:string; cancelled_at:string|null; cancellation_reason:string|null; refund_amount:number|null; bp_plots?:BpPlot; bp_customers?:BpCustomer; brokers?:Broker; bp_projects?:BpProject }
export interface BpPayment { id:string; booking_id:string; customer_id:string|null; payment_type:string; amount:number; payment_mode:string; utr_ref:string|null; cheque_no:string|null; bank_name:string|null; payment_date:string; received_by:string|null; receipt_no:string|null; notes:string|null; created_at:string }
export interface BpPayoutTransaction { id:string; broker_id:string; booking_id:string|null; payout_type:string; amount:number; status:string; payment_mode:string|null; utr_ref:string|null; paid_date:string|null; approved_by:string|null; notes:string|null; created_at:string; updated_at:string; tds_amount:number|null; net_amount:number|null; approver_name:string|null; bank_ref:string|null; rejection_reason:string|null; brokers?:Broker; bp_bookings?:BpBooking }
export interface BpCommissionRule { id:string; project_id:string|null; broker_rank:string|null; stage:string|null; commission_pct:number|null; flat_amount:number|null; min_collection_pct:number|null; is_active:boolean; notes:string|null; created_at:string; updated_at:string; bp_projects?:BpProject }
export interface BpBrokerBank { id:string; broker_id:string; account_name:string; account_no:string; ifsc:string; bank_name:string; branch:string|null; account_type:string|null; is_primary:boolean; verified:boolean; created_at:string; updated_at:string }
export interface BpBrokerKyc { id:string; broker_id:string; doc_type:string; doc_label:string|null; file_url:string|null; file_name:string|null; verified:boolean; verified_by:string|null; verified_at:string|null; notes:string|null; created_at:string }
export interface BpPlotHoldLog { id:string; plot_id:string; broker_id:string|null; customer_name:string|null; held_by:string|null; hold_reason:string|null; hold_from:string|null; hold_until:string|null; released_at:string|null; released_by:string|null; status:string; created_at:string }
export interface CrmLead { id:string; name:string; phone:string; alt_phone:string|null; email:string|null; source:string|null; project_id:string|null; assigned_to:string|null; status:string; pickup_status:string|null; lost_reason:string|null; budget_min:number|null; budget_max:number|null; quick_note:string|null; tags:string[]; next_follow_up_at:string|null; last_called_at:string|null; call_attempts:number; created_at:string; updated_at:string }
export interface CrmLeadInteraction { id:string; lead_id:string; user_id:string|null; kind:string; note:string|null; tags:string[]; pickup_status:string|null; next_follow_up_at:string|null; created_at:string }
export interface BpCustomerLedger { id:string; customer_id:string; booking_id:string|null; entry_type:string; amount:number; balance_after:number; description:string|null; ref_payment_id:string|null; entry_date:string; created_by:string|null; created_at:string }